name: DevSecOps Juice Shop

on:
  push:
    branches: [ main ]

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t juice-shop .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'juice-shop'
        severity: 'HIGH,CRITICAL'

    - name: SAST Scan with Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: 'auto'

    - name: Secrets Scan with GitLeaks
      uses: gitleaks/gitleaks-action@v2

    - name: Run Juice Shop in background
      run: docker run -d -p 3000:3000 --name juice bkimminich/juice-shop

    - name: Wait for app to be ready
      run: sleep 15

    - name: DAST Scan with OWASP ZAP
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
