name: DevSecOps Juice Shop

on:
  push:
    branches: [ main ]

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t juice-shop .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'juice-shop'
        severity: 'HIGH,CRITICAL'

    - name: Install Semgrep
      run: |
        pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep --config=auto || true

    - name: Secrets Scan with GitLeaks (ignore exit code)
      run: |
        curl -sL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        ./gitleaks detect --redact || true

    - name: Run Juice Shop in background
      run: docker run -d -p 3000:3000 --name juice bkimminich/juice-shop

    - name: Wait for app to be ready
      run: sleep 15

    - name: DAST Scan with OWASP ZAP
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
      continue-on-error: true

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Tag and Push image to DockerHub
      run: |
        docker tag juice-shop ${{ secrets.DOCKERHUB_USERNAME }}/juice-shop:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/juice-shop:latest
